services:
  php-apache:
    container_name: php-apache
    build:
      context: php
      dockerfile: Dockerfile
    volumes:
      - ./php:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
  
  mysql:
    container_name: mysql_php
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Q@wertyuiop
      MARIADB_DATABASE: komis
      MARIADB_USER: komis
      MARIADB_PASSWORD: Q@wertyuiop
    ports:
      - 3308:3306
    build:
      context: sql
      dockerfile: Dockerfile

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    restart: always
    environment:
      PMA_HOST: mysql_php
    depends_on:
      - mysql